@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@questionId = 

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Wick1",
    "email": "boogeyman@example2.com.br",
    "password": "6669992"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "boogeyman@example2.com.br",
    "password": "6669992"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "John's Check2",
    "content": "Are you sure you want to do this?2"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
POST {{baseUrl}}/questions/1d124415-77f9-4064-bd94-d79d60606f7f/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "content": "Yes, let's dance! >)"
}

###

# @name get_question-by_slug
GET {{baseUrl}}/questions/johns-check
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

#